
import System.Directory
import System.Environment
import System.Process

eliminateFiles :: Bool -> FilePath -> String
eliminateFiles eraseInps path
  | eraseInps == True = "rm " ++ path ++ "/*.gbw " ++ path ++ "/*.job " ++ path ++ "/*.o* " ++ path ++ "/*.qro " ++ path ++ "/*.unso " ++ path ++ "/*.uno " ++ path ++ "/*.prop " ++ path ++ "/*.loc " ++ path ++ "/*.inp"
  | otherwise         = "rm " ++ path ++ "/*.gbw " ++ path ++ "/*.job " ++ path ++ "/*.o* " ++ path ++ "/*.qro " ++ path ++ "/*.unso " ++ path ++ "/*.uno " ++ path ++ "/*.prop " ++ path ++ "/*.loc"

main = do
  -- Get the target directory
  args <- getArgs
  -- Get contents of the current repository
  if length args > 0 then do
    repo <- setCurrentDirectory (args !! 0)
    putStrLn "Target directory set \n"
    else do
    putStrLn "This program eliminates all the files generated by orca except the xyz files .. "
    putStrLn ""
    putStrLn "Arguments:"
    putStrLn "           - path to the directry in which the operation will be performed "
    putStrLn "           - if \"true\" is optionally given as a second argument the .inp files are also eliminated "        
    putStrLn ""    
    error "Aborting further operation"

  -- If this is true, erase .inp files as well 
  let eraseInps = if length args > 1 then ((args !! 1) == "True") || ((args !! 1) == "true") else False
  
  -- Get contents of the current repository
  dirs <- getCurrentDirectory
  cons <- getDirectoryContents dirs
  
  callCommand $ eliminateFiles eraseInps dirs
  
  print "End"

  
